ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ org.kotatsu.ApplicationKt.module ]
    }
}
jwt {
    secret = "default_secret"
    secret = ${?JWT_SECRET}
    issuer = "http://0.0.0.0:8080/"
    audience = "http://0.0.0.0:8080/resource"
}
database {
    name = "defaultdb"
    name = ${?DATABASE_NAME}
    dialect = "mysql"
    dialect = ${?DATABASE_DIALECT}
    host = "localhost"
    host = ${?DATABASE_HOST}
    port = 3306
    port = ${?DATABASE_PORT}
    user = ${?DATABASE_USER}
    password = ${?DATABASE_PASSWORD}
    params = "?sslMode=REQUIRED"
}
kotatsu {
    allow_new_register = true
    allow_new_register = ${?ALLOW_NEW_REGISTER}
    mail_provider = "console"
    mail_provider = ${?MAIL_PROVIDER}
    base_url = "http://localhost:8080"
    base_url = ${?BASE_URL}
}
smtp {
    host = ${?SMTP_HOST}
    port = ${?SMTP_PORT}
    username = ${?SMTP_USERNAME}
    password = ${?SMTP_PASSWORD}
    from = ${?SMTP_FROM}
}
